---
title: "作業二：迴歸分析與其進階型態"
author: "吳永健"
date: "2023-04-22"
output: html_document
---

# 作業二：迴歸分析與其進階型態

## 重製葉高華，2017，〈臺灣民眾的家庭語言選擇〉，《臺灣社會學刊》62：59-111。

# 前置準備

```{r}
# 需要套件
library(haven)
library(dplyr)
library(gmodels)
library(openxlsx)
library(stargazer)

# 設定工作路徑
setwd("D:/Dropbox/學習/碩士/碩一下/量化分析專題/hw/hw2/")

# 讀入資料
identity <- read_dta("C00224_2/tscs2013q2.dta", encoding = "Big5") 

```

# 分析開始

## 選取需要的變項

```{r}
working <- c("v16", "v18a", "v13", "v8", "v11", "v1", "year", "v2y", 
           "v21", "kv21_0", "v99", "v102b4", "v102b5", "v102d", 
           "v100", "v58", "v59")
r_iden <- identity[working]
names(r_iden)
```

## 建立變項

### 變數定義：使用語言

```{r}
### /* 將家裡最常講語言recode，並轉成factor */
r_iden <- r_iden %>% 
  mutate(
    language_home = case_match(
      v16, 1 ~ 1, 2 ~ 2, c(3, 6, 7) ~ 3, 5 ~ 4,
      .default = NA
    )) %>% 
  transform(
    language_home = factor(
      language_home,
      levels = c(1, 2, 3, 4),
      labels = c("華語", "閩南語", "包含客語", "華語+閩南語")
      ))

### /*二元變項 最常說華語*/
r_iden <- r_iden %>% 
  mutate(
    chinese_home = case_match(
      as.numeric(language_home), 1 ~ 1, c(2, 3, 4) ~ 0,
      .default = NA
      ))

### /*二元變項 最常說閩南語*/
r_iden <- r_iden %>% 
  mutate(
    minnan_home = case_match(
      as.numeric(language_home), 2 ~ 1, c(1, 3, 4) ~ 0,
      .default = NA
      ))

### /* 將家裡最希望講語言recode，並轉成factor */
r_iden <- r_iden %>% 
  mutate(
    language_hope = ifelse(v18a >= 90, NA_real_, v18a)
    ) %>%
  transform(
    language_hope = factor(
      language_hope,
      levels = c(1, 2, 3, 4),
      labels = c("華語", "閩南語", "客語", "其他")
      ))

### /*二元變項 最希望華語*/
r_iden <- r_iden %>% 
  mutate(
    chinese_hope = case_match(
      as.numeric(language_hope), 1 ~ 1, c(2, 3, 4) ~ 0,
      .default = NA
      ))
### /*二元變項 最希望閩南語*/
r_iden <- r_iden %>% 
  mutate(
    minnan_hope = case_match(
      as.numeric(language_home), 2 ~ 1, c(1, 3, 4) ~ 0,
      .default = NA
      ))
```

### 變數定義：解釋變項

```{r}
### 雙親族群 9類
r_iden <- r_iden %>% 
  mutate(
    parent_ethnic_g9 = 
      ifelse(v8 == 1 & v11 == 1, 1, #福-福
        ifelse(v8 == 1 & v11 == 2, 2, #福-客
          ifelse(v8 == 1 & (v11 == 4 | v11 == 5), 3, # 福-外
            ifelse(v8 == 2 & v11 == 1, 4, #客-福
              ifelse(v8 == 2 & v11 == 2, 5, #客-客
                ifelse(v8 == 2 & (v11 == 4 | v11 == 5), 6, #客-外
                  ifelse((v8 == 4 | v8 == 5) & v11 == 1, 7, #外-福
                    ifelse((v8 == 4 | v8 == 5) & v11 == 2, 8, #外-客
                      ifelse((v8 == 4 | v8 == 5) & (v11 == 4 | v11 == 5), 9, NA #外-外
                       )))))))))) %>% 
    transform(
    parent_ethnic_g9 = factor(
      parent_ethnic_g9,
      levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9),
      labels = c("福-福", "福-客", "福-外", "客-福", "客-客", "客-外",
                 "外-福", "外-客", "外-外")
      ))

### 雙親族群 6類              
r_iden <- r_iden %>% 
  mutate(
    parent_ethnic_g6 = case_match(
      as.numeric(parent_ethnic_g9), 1 ~ 1, c(2, 4) ~ 2, c(3, 7) ~ 3, 5 ~ 4, 
                                    c(6, 8) ~ 5, 9 ~ 6,
      .default = NA
    )) %>% 
  transform(
    parent_ethnic_g6 = factor(
      parent_ethnic_g6,
      levels = c(1, 2, 3, 4, 5, 6),
      labels = c("福佬", "福佬+客家", "福佬+外省", "客家", "客家+外省", "外省")
      ))

### 雙親族群 4類              
r_iden <- r_iden %>% 
  mutate(
    parent_ethnic_g4 = case_match(
      as.numeric(parent_ethnic_g9), 1 ~ 1, c(2, 4) ~ 2, c(3, 7) ~ 3,
                                    c(5, 6, 8, 9) ~ 4,
      .default = NA
    )) %>% 
  transform(
    parent_ethnic_g4 = factor(
      parent_ethnic_g4,
      levels = c(1, 2, 3, 4),
      labels = c("福佬", "福佬+客家", "福佬+外省", "皆非福佬")
      ))

### 性別
r_iden <- r_iden %>% 
  mutate(
    female = case_match(
      v1, 1 ~ 0, 2 ~ 1,
      .default = NA
      )) %>% 
    transform(
    female = factor(
      female,
      levels = c(0, 1),
      labels = c("男", "女")
      ))

### 出生世代
r_iden <- r_iden %>% 
  mutate(
    age_g6= case_match(
      v2y, c(0:34) ~ 1, c(35:44) ~ 2, c(45:54) ~ 3, c(55:64) ~ 4, c(65:74) ~ 5,
           c(75:83) ~ 6, .default = NA
    )) %>% 
  transform(
    age_g6 = factor(
      age_g6,
      levels = c(1, 2, 3, 4, 5, 6),
      labels = c("1945以前", "1946~1955", "1956~1965", "1966~1975", "1976~1985",
                 "1986~1994")
      ))

### 教育程度
r_iden <- r_iden %>% 
  mutate(
    edu_g6 = case_match(
      v21, c(1, 2, 3) ~ 1, c(4, 5) ~ 2, c(6:9) ~ 3, c(10:18, 22) ~ 4, 19 ~ 5,
           c(20, 21) ~ 6, .default = NA)
    ) %>% 
  transform(
    edu_g6 = factor(
      edu_g6,
      levels = c(1, 2, 3, 4, 5, 6),
      labels = c("小學以下", "國中", "高中職", "專科", "大學", "研究所以上")
      ))

### 階級
r_iden <- r_iden %>% 
  mutate(
    class_g4 = 
      ifelse(v102d == 1, 1, #雇主
        ifelse(v102d == 2, 2, #自營作業者
          ifelse(v102b5 >= 1100 & v102b5 <= 3999, 3, #新中產階級
          ifelse(v102b5 >= 4000 & v102b5 <= 9333, 4, NA  #非技術工人
                 ))))) %>% 
  transform(
    class_g4 = factor(
      class_g4,
      levels = c(4, 1, 2, 3), # 非技術工人 為參考組
      labels = c("非技術工人", "雇主", "自營作業者", "新中產階級") 
      ))

### 台灣人認同
r_iden <- r_iden %>% 
  mutate(
    id_taiwan = ifelse(v58 >= 90, NA, v58)
  )

### 中國人認同
r_iden <- r_iden %>% 
  mutate(
    id_china = ifelse(v59 >= 90, NA, v59)
  )

### 排除缺失值
reglist <- r_iden[c("language_home", "language_hope", "parent_ethnic_g9",
                   "female", "age_g6", "edu_g6", "class_g4", "id_taiwan",
                   "id_china")]

c_r_iden <- r_iden[complete.cases(reglist),]

```

# 資料分析

```{r}
# 表1、在家裡最常說的語言與解釋變項的交叉表

# 製作交叉表
t1_1 <- CrossTable(c_r_iden$parent_ethnic_g9, c_r_iden$language_home, 
                   prop.r = TRUE, chisq = TRUE)
t1_2 <- CrossTable(c_r_iden$female, c_r_iden$language_home, 
                   prop.r = TRUE, chisq = TRUE)
t1_3 <- CrossTable(c_r_iden$age_g6, c_r_iden$language_home, 
                   prop.r = TRUE, chisq = TRUE)
t1_4 <- CrossTable(c_r_iden$edu_g6, c_r_iden$language_home, 
                   prop.r = TRUE, chisq = TRUE)
t1_5 <- CrossTable(c_r_iden$class_g4, c_r_iden$language_home, 
                   prop.r = TRUE, chisq = TRUE)


# 將列百分比取出並合併多個交叉表

total_1 <- c(rep(1, 27))
# /*取出卡方值*/
chi_1 <- c(t1_1$chisq$statistic, rep(NA, 8), t1_2$chisq$statistic, rep(NA, 1),
           t1_3$chisq$statistic, rep(NA, 5), t1_4$chisq$statistic, rep(NA, 5),
           t1_5$chisq$statistic, rep(NA, 3))
# /*取出P值*/
pvalue_1 <- c(t1_1$chisq$p.value, rep(NA, 8), t1_2$chisq$p.value, rep(NA, 1),
           t1_3$chisq$p.value, rep(NA, 5), t1_4$chisq$p.value, rep(NA, 5),
           t1_5$chisq$p.value, rep(NA, 3))

t1 <- as.data.frame(cbind(rbind(t1_1$prop.row, t1_2$prop.row, t1_3$prop.row, 
                                t1_4$prop.row, t1_5$prop.row), 
                          total_1, chi_1, pvalue_1))

#輸出表
table_output <- createWorkbook() 

# 新增工作表，命名為 表1
addWorksheet(table_output, "表1")
writeData(table_output, "表1", t1, colNames = TRUE, rowNames = TRUE)

```

```{r}
# 表2、在家裡最希望跟小孩說的語言與解釋變項的交叉表
# 製作交叉表
t2_1 <- CrossTable(c_r_iden$parent_ethnic_g9, c_r_iden$language_hope, 
                   prop.r = TRUE, chisq = TRUE)
t2_2 <- CrossTable(c_r_iden$female, c_r_iden$language_hope, 
                   prop.r = TRUE, chisq = TRUE)
t2_3 <- CrossTable(c_r_iden$age_g6, c_r_iden$language_hope, 
                   prop.r = TRUE, chisq = TRUE)
t2_4 <- CrossTable(c_r_iden$edu_g6, c_r_iden$language_hope, 
                   prop.r = TRUE, chisq = TRUE)
t2_5 <- CrossTable(c_r_iden$class_g4, c_r_iden$language_hope, 
                   prop.r = TRUE, chisq = TRUE)


# 將列百分比取出並合併多個交叉表

total_2 <- c(rep(1, 27))
# /*取出卡方值*/
chi_2 <- c(t2_1$chisq$statistic, rep(NA, 8), t2_2$chisq$statistic, rep(NA, 1),
           t2_3$chisq$statistic, rep(NA, 5), t2_4$chisq$statistic, rep(NA, 5),
           t2_5$chisq$statistic, rep(NA, 3))
# /*取出P值*/
pvalue_2 <- c(t2_1$chisq$p.value, rep(NA, 8), t2_2$chisq$p.value, rep(NA, 1),
           t2_3$chisq$p.value, rep(NA, 5), t2_4$chisq$p.value, rep(NA, 5),
           t2_5$chisq$p.value, rep(NA, 3))

t2 <- cbind(
      rbind(t2_1$prop.row, t2_2$prop.row, t2_3$prop.row, t2_4$prop.row,
            t2_5$prop.row), total_2, chi_2, pvalue_2)

#輸出表2
addWorksheet(table_output, "表2")
writeData(table_output, "表2", t2, colNames = TRUE, rowNames = TRUE)

saveWorkbook(table_output, "hw2_表1-2.xlsx", overwrite = TRUE)

```

```{r}
# 表3、重製葉高華的表1

t2_m1_1 <- glm(formula = chinese_home ~ parent_ethnic_g6 + female + age_g6 +
                       class_g4,
                       family = binomial, data = c_r_iden)
t2_m1_2 <- glm(formula = chinese_home ~ parent_ethnic_g6 + female + age_g6 +
                       edu_g6 + class_g4,
                       family = binomial, data = c_r_iden)
t2_m2_1 <- glm(formula = chinese_hope ~ parent_ethnic_g6 + female + age_g6 +
                         class_g4,
                       family = binomial, data = c_r_iden)
t2_m2_2 <- glm(formula = chinese_hope ~ parent_ethnic_g6 + female + age_g6 +
                       edu_g6 + class_g4,
                       family = binomial, data = c_r_iden)
t2_m2_3 <- glm(formula = chinese_hope ~ parent_ethnic_g6 + female + age_g6 +
                       edu_g6 + class_g4 + id_taiwan + id_china,
                       family = binomial, data = c_r_iden)
#利用stargazer來整理報表

stargazer(t2_m1_1, t2_m1_2, t2_m2_1, t2_m2_2, t2_m2_3,
          type = "text", ci = FALSE, digits = 2, 
          star.cutoffs = c(.05, .01, .001),
          title = "表3 選擇華語的迴歸分析",
          covariate.labels = 
            c("福佬+客家", "福佬+外省", "客家", "客家+外省", "外省", "女",
              "1946~1955", "1956~1965", "1966~1975", "1976~1985", "1986~1994",
              "國中", "高中職", "專科", "大學", "研究所以上", "雇主", 
              "自營作業者","新中產階級","台灣人認同", "中國人認同",
              "Intercept"),
          dep.var.labels = c("最常說華語", "最希望跟小孩說華語"),
          column.labels = c("m1_1", "m1_2",
                          "m2_1", "m2_2", "m2_3"),
          align = TRUE , multicolumn = TRUE, out = "hw2_表3.html")


```

```{r}
# 表4、重製葉高華的表2

t3_m3_1 <- glm(formula = minnan_home ~ parent_ethnic_g4 + female + age_g6 +
                       class_g4,
                       family = binomial, data = c_r_iden)
t3_m3_2 <- glm(formula = minnan_home ~ parent_ethnic_g4 + female + age_g6 +
                       edu_g6 + class_g4,
                       family = binomial, data = c_r_iden)
t3_m4_1 <- glm(formula = minnan_hope ~ parent_ethnic_g4 + female + age_g6 +
                         class_g4,
                       family = binomial, data = c_r_iden)
t3_m4_2 <- glm(formula = minnan_hope ~ parent_ethnic_g4 + female + age_g6 +
                       edu_g6 + class_g4,
                       family = binomial, data = c_r_iden)
t3_m4_3 <- glm(formula = minnan_hope ~ parent_ethnic_g4 + female + age_g6 +
                       edu_g6 + class_g4 + id_taiwan + id_china,
                       family = binomial, data = c_r_iden)
#利用stargazer來整理報表

stargazer(t3_m3_1, t3_m3_2, t3_m4_1, t3_m4_2, t3_m4_3,
          type = "text", ci = FALSE, digits = 2, 
          star.cutoffs = c(.05, .01, .001),
          title = "表4 選擇閩南語的迴歸分析",
          covariate.labels = 
            c("福佬+客家", "福佬+外省", "皆非福佬", "女",
              "1946~1955", "1956~1965", "1966~1975", "1976~1985", "1986~1994",
              "國中", "高中職", "專科", "大學", "研究所以上", "雇主", 
              "自營作業者","新中產階級","台灣人認同", "中國人認同",
              "Intercept"),
          dep.var.labels = c("最常說閩南語", "最希望跟小孩說閩南語"),
          column.labels = c("m3_1", "m3_2",
                            "m4_1", "m4_2", "m4_3"),
          align=TRUE, multicolumn = TRUE, out = "hw2_表4.html")

```




```{r}
library(Statamarkdown)
stataexe <- "D:/Stata 17/StataMP-64.exe"
knitr::opts_chunk$set(engine.path=list(stata=stataexe))

```

```{stata}
cd "D:\Dropbox\工作\中研院_工作\ABSW5 Attitudes toward China\"


import excel "10 data\macro\指標_230426.xlsx", ///
       sheet("工作表1") cellrange(A1:F16) firstrow clear
       
tab country_nm
help lab
```


```{r}
library(RStata)

chooseStataBin()
options("RStata.StataVersion" = 17)

stata('di "Hello World"')
stata('di 2+2')
stata('clear all')
```



