---
title: "作業四：結構方程式模型"
author: "吳永健"
date: "`r Sys.Date()`"
output: html_document
---

# 作業三：長期資料分析
# 重製劉宗幸與江守峻（2020）

# 前置準備

```{r eval=FALSE}
# 需要套件
library(haven)
library(tidyverse)
library(lavaan)
library(semPlot)
library(sjmisc) ## 設置缺失值
library(sjlabelled) ## 上標籤用
library(magrittr)
library(semPlot)

#設定工作路徑
setwd("D:/Dropbox/學習/碩士/碩一下/量化分析專題/hw/hw4")

# 讀入資料
w <- read_dta("data/data1.dta") ## 已經改過編碼了

```

# 分析開始

## 選取需要的變項
```{r}
# 選取需要的變項
working <- c("relationship", "pfa0201", "pfa0202", "pfa1101", "pfa1102",
             "famedu01", "famedu02", "famedu03", ## 管
             "famedu04", "famedu05", ## 教
             "famedu06", "famedu07", ## 成就期待
             "famc01", "famc02", "famevic01", "famc08", ## 環境多樣
             "famc03", "famc04","famc05", "famc06", "famc07", ## 學習材料 
             "famc09", "famc10", "famc11", "famc12", "famc13", ## 學習刺激
             "famc14", "famc15", "famc16", ## 父母回應
             "famc17","famc18", "famc19" ## 條件式管教
             )

rw <- w[working]

working2 <- c("famedu01", "famedu02", "famedu03", ## 管
             "famedu04", "famedu05", ## 教
             "famedu06", "famedu07", ## 成就期待
             "famc01", "famc02", "famevic01", "famc08", ## 環境多樣
             "famc03", "famc04","famc05", "famc06", "famc07", ## 學習材料 
             "famc09", "famc10", "famc11", "famc12", "famc13", ## 學習刺激
             "famc14", "famc15", "famc16", ## 父母回應
             "famc17","famc18", "famc19" ## 條件式管教
             )
## 將原先教養信念及家庭學習環境的5(拒答) 設成9999
rw[, working2] <- lapply(rw[ ,working2],
                         function(var)
                           ifelse(var >= 5, 9999, var)
                         )


# 篩選觀察值
## 以「成對刪除法」刪除教養信念及家庭學習環境有 3 題以上未填答者
## 拒答和遺漏是9999，全部加起來小於9999*3+1*27=30024 就不是3 題以上未填答者
## 與幼兒關係為親生父母、養父母及繼父母
rw %<>% 
  mutate(
    testna = (famedu01 + famedu02 + famedu03 ## 管
            + famedu04 + famedu05 ## 教
            + famedu06 + famedu07 ## 成就期待
            + famc01 + famc02 + famevic01 + famc08 ## 環境多樣
            + famc03 + famc04 + famc05 + famc06 + famc07 ## 學習材料 
            + famc09 + famc10 + famc11 + famc12 + famc13 ## 學習刺激
            + famc14 + famc15 + famc16 ## 父母回應
            + famc17 + famc18 + famc19 ## 條件式管教
            )  
  )%>% 
  filter(testna <= 30024 & relationship <= 8)

# 再把因子的不合理直改成NA
rw[, working2] <- lapply(rw[ ,working2],
                         function(var)
                           ifelse(var >= 5, NA_integer_, var)
                         )
```

## 建立變項
```{r}
# 社經地位
## 林生傳（2005）是分數越大越低社經，但文章好像是分數越大越高社經
rw %<>% 
  mutate(
    ## 父親教育5分數
    edu5_f =  case_match(
      pfa0201, 6 ~ 5, c(4, 5) ~ 4, c(2, 3) ~ 3, 1 ~ 2,
      .default = 0
    ),
    ## 母親教育5分數
    edu5_m =  case_match(
      pfa0202, 6 ~ 5, c(4, 5) ~ 4, c(2, 3) ~ 3, 1 ~ 2,
      .default = 0
    ),
    ##父親階級5分數
    class5_f =  case_match(
      pfa1101, c(1, 2) ~ 5, c(3, 4) ~ 4, 5 ~ 3, c(6, 7, 9, 10) ~ 2,
               c(8, 10:13) ~ 1,
      .default = 0
    ),
    ##母親階級5分數
    class5_m =  case_match(
      pfa1101, c(1, 2) ~ 5, c(3, 4) ~ 4, 5 ~ 3, c(6, 7, 9, 10) ~ 2,
               c(8, 10:13) ~ 1,
      .default = 0
    )
  ) %>% 
  mutate(
    ## 取父母教育程度大的
    edu5 = ifelse(edu5_f > edu5_m, edu5_f, edu5_m),
    ## 取父母階級大的
    class5 = ifelse(class5_f > class5_m, class5_f, class5_m)
  ) %>%
  filter(edu5 != 0 & class5 != 0) %>%   ## 刪除教育或階級分數缺失者
  mutate(
    ses = edu5*4 + class5*7
  ) 
```

## 選取分析資料
```{r}

analysis <- subset(rw, select = c(-relationship, -pfa0201, -pfa0202, 
                                  -pfa1101, -pfa1102, -testna, -edu5_f,
                                  -edu5_m, -class5_f, -class5_m, -edu5, 
                                  -class5, -famedu04, -famedu05, -famedu06,
                                  -famedu07))
```

# 資料分析
```{r}
#圖一、表五
med1 <- '
discipline =~ famedu01 + famedu02 + famedu03
env_dir =~ famc01 + famc02 + famevic01 + famc08
materials =~ famc03 + famc04 + famc05 + famc06 + famc07
stimulation =~ famc09 + famc10 + famc11 + famc12 + famc13
respons =~ famc14 + famc15 + famc16
c_discipline =~ famc17 + famc18 + famc19

discipline ~ a*ses

env_dir ~ b*ses + c*discipline
materials ~ d*ses + e*discipline
stimulation ~ f*ses + g*discipline
respons ~ h*ses + i*discipline
c_discipline ~ j*ses + k*discipline

ac:=a*c
total1:=b+(a*c)
ae:=a*e
total2:=d+(a*e)
ag:=a*g
total3:=f+(a*g)
ai:=a*i
total4:=i+(a*i)
ak:=a*k
total5:=j+(a*k)'


set.seed(1234)
fitmed1<-sem(med1, data = analysis, 
             se = "bootstrap", bootstrap = 1000, missing = 'fiml')
summary(fitmed1, standardized=TRUE, fit.measures = TRUE)


#semPaths(fitmed1, "par", weighted = FALSE, nCharNodes = 7, shapeMan = "rectangle",
#         sizeMan = 8, sizeMan2 = 5)
```




